### ISSUE TITLE
Add additional data to summary endpoint or create a new endpoint with the new requested data

### ISSUE THREAD

**Issue by gcharang** [tonymorony/dexstats_sqlite_py#10]
https://stats.testchain.xyz:8080/api/v1/summary
Example:
```json
[
{
"trading_pair": "BTC-BEP20_USDT-BEP20",
"last_price": "0.0000000000",
"lowest_ask": "0.0000000000",
"highest_bid": "0.0000000000",
"base_currency": "BTC-BEP20",
"base_volume": "0.0000000000",
"quote_currency": "USDT-BEP20",
"quote_volume": "0.0000000000",
"price_change_percent_24h": "0.0000000000",
"highest_price_24h": "0.0000000000",
"lowest_price_24h": "0.0000000000"
},
{}]
```
Add key-values that give:
1) `last_swap` : timestamp of latest successful swap for the pair in utc. epoch format may be good
2)  `no_of_trades` : no. of trades in the last 24H for this pair

these details can be used in the markets tab of markets.atomicdex.io

**Comment by tonymorony** [comment]
Hi! This info you can get from:
https://stats.testchain.xyz:8080/api/v1/trades/KMD_MCL/1 (num of trades is response list length, last trade is one with the biggest timestamp)
Please let me know if it's not comfortable enough

**Comment by gcharang** [comment]
> stats.testchain.xyz:8080/api/v1/trades/KMD_MCL/1 

can be used. but, using it means the frontend will have to send 100 requests to display 100 rows on the same page. getting all the data in a single request will be optimal imo

**Comment by tonymorony** [comment]
got it 👍
sure, will add it to this RPC call since it's needed for all pairs on the same screen

**Comment by tonymorony** [comment]
@gcharang added new keys to https://stats.testchain.xyz:8080/api/v1/summary

e.g. `"trades_24h":1,"last_swap_timestamp":1624137500`
