### ISSUE TITLE
Limit numbers in responses to 8 decimal places

### ISSUE THREAD

**Issue by gcharang** [tonymorony/dexstats_sqlite_py#7]
Example: https://stats.testchain.xyz:8080/api/v1/orderbook/KMD_BTC

**Comment by tonymorony** [comment]
I think it's better to keep precision received from mm2 on the API side in case if this API will be used in some trading operations / calculations (to not accumulate rounding error) and round by frontend where it looks not cute (and show full precision on mouse hover lets say)

note that non-UTXO assets (native and non-native platforms tokens) might have different denomination / smallest parts e.g. ERC20 contract decimals() uint8 so can contain up to 255 decimals (https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#ERC20-decimals--)

0.000000000000001 price of some non popular ERC20 token in relation to BTC imaginable case so 8 decimal might be not the ultimate choice in all places
