### ISSUE TITLE
Request: Summary endpoint that gives details of all the available currencies

### ISSUE THREAD

**Issue by gcharang** [tonymorony/dexstats_sqlite_py#8]
it could work similar to https://stats.testchain.xyz:8080/api/v1/fiat_rates
and it can also provide details like: 
a) volume of each coin in the last 24H
b) number of trades a coin was involved in the last 24 hrs

This can be used to display data on the landing page like this:

![Screenshot from 2021-05-06 11-33-28](https://user-images.githubusercontent.com/21151592/117249271-ecec4c80-ae5e-11eb-8a0a-8838da6de431.png)

**Comment by tonymorony** [comment]
added requested data into https://stats.testchain.xyz:8080/api/v1/tickers_summary
